<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PageBuilder\BaseWidget'                   => __DIR__ . '/src/PageBuilder/BaseWidget.php',
  'PageBuilder\Controller\AjaxController'    => __DIR__ . '/src/PageBuilder/Controller/AjaxController.php',
  'PageBuilder\Entity\Page'                  => __DIR__ . '/src/PageBuilder/Entity/Page.php',
  'PageBuilder\Entity\Template'              => __DIR__ . '/src/PageBuilder/Entity/Template.php',
  'PageBuilder\Entity\TemplateSection'       => __DIR__ . '/src/PageBuilder/Entity/TemplateSection.php',
  'Application\Exception'                    => __DIR__ . '/src/PageBuilder/Exception.php',
  'PageBuilder\Navigation\NavigationFactory' => __DIR__ . '/src/PageBuilder/Navigation/NavigationFactory.php',
  'PageBuilder\View\Helper\PageBuilder'      => __DIR__ . '/src/PageBuilder/View/Helper/PageBuilder.php',
  'PageBuilder\View\TagAttributes'           => __DIR__ . '/src/PageBuilder/View/TagAttributes.php',
  'PageBuilder\Widget\Core\Gap'              => __DIR__ . '/src/PageBuilder/Widget/Core/Gap.php',
  'PageBuilder\Widget\Core\MainContent'      => __DIR__ . '/src/PageBuilder/Widget/Core/MainContent.php',
  'PageBuilder\Widget\Core\SmallGap'         => __DIR__ . '/src/PageBuilder/Widget/Core/SmallGap.php',
  'PageBuilder\Widget\Core\StatusMessages'   => __DIR__ . '/src/PageBuilder/Widget/Core/StatusMessages.php',
  'PageBuilder\WidgetFactory'                => __DIR__ . '/src/PageBuilder/WidgetFactory.php',
  'PageBuilder\WidgetInterface'              => __DIR__ . '/src/PageBuilder/WidgetInterface.php',
  'PageBuilderTest\BaseTestClass'            => __DIR__ . '/tests/BaseTestClass.php',
  'PageBuilderTest\Bootstrap'                => __DIR__ . '/tests/bootstrap.php',
  'PageBuilderTest\Classes\GridTest'         => __DIR__ . '/tests/classes/GridTest.php',
  'PageBuilderTest\TestAdapter'              => __DIR__ . '/tests/TestAdapter.php',
);
