<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/index'                           => __DIR__ . '/view/error/404.phtml',
    'error/404'                           => __DIR__ . '/view/error/index.phtml',
    'layout/layout'                       => __DIR__ . '/view/layout/layout.phtml',
    'layout/partials/common-api-response' => __DIR__ . '/view/layout/partials/common-api-response.phtml',
    'layout/partials/user-message'        => __DIR__ . '/view/layout/partials/user-message.phtml',
    'page-builder/index/admin'            => __DIR__ . '/view/page-builder/index/admin.phtml',
    'page-builder/index/index'            => __DIR__ . '/view/page-builder/index/index.phtml',
);
