<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Bootstrap'                     => __DIR__ . '/Bootstrap.php',
  'PageBuilderTest\Module'        => __DIR__ . '/module/Module.php',
  'PageBuilderTest\BaseTestClass' => __DIR__ . '/module/PageBuilderTest/BaseTestClass.php',
  'PageBuilderTest\Test\PageTest' => __DIR__ . '/module/PageBuilderTest/Test/PageTest.php',
);
