<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Synergy Page Builder')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(
        array('rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
              'href' => $this->basePath() . '/img/favicon.ico')
    )
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-2.3/bootstrap-responsive.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-2.3/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/css/jqueryui/smoothness/jquery-ui.min.css')
        ->appendStylesheet($this->basePath() . '/css/jqueryui/smoothness/jquery.ui.theme.css')
        ->appendStylesheet($this->basePath() . '/jqGrid/css/ui.jqgrid.css')
        ->appendStylesheet($this->basePath() . '/plugin/pagebuilder/css/pagebuilder.min.css')

    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->appendFile($this->basePath() . '/jqGrid/js/i18n/grid.locale-en.js')
        ->appendFile($this->basePath() . '/jqGrid/src/jquery.jqGrid.js')
        ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js');
    ?>
    <script src="<?php echo $this->basePath() . '/plugin/pagebuilder/libs/require.min.js'; ?>" type="text/javascript"
            data-main="<?php echo $this->basePath() . '/plugin/pagebuilder/libs/app'; ?>"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('pagebuilder\home') ?>"><?php echo $this->translate('Synergy Page Builder') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="<?php echo $this->url('pagebuilder\home') ?>"><?php echo $this->translate('Home') ?></a>
                <li class="active"><a href="<?php echo $this->url('pagebuilder\admin') ?>"><?php echo $this->translate('Demo') ?></a>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->buildPage($this->content); ?>
    <hr>
    <footer>
        <p>&copy; 2006 - <?php echo date('Y') ?> by Rhema Studio Limited. <?php echo $this->translate(
                'All rights reserved.'
            ) ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</body>
</html>
